
export const SCREEN_NAME = {
  HOME: "Home",
  BOTTOM_TAB: "BottomTab",
  PROFILE: "Profile",
  SETTINGS: "Settings",
  LOGIN: "Login",
  REGISTER: "Register",
  TESTING: "Testing",
  LIBRARY: "Library",
  SEARCH: "Search",
  AlbumScreen: "AlbumScreen",
  PlaylistScreen: "PlaylistScreen",
  START: 'Start',
  SIGNUP_EMAIL: 'SignUpEmail',
  SIGNUP_PASSWORD: 'SignUpPassword',
  SIGNUP_GENDER: 'SignUpGender',
  SIGNUP_NAME: 'SignUpName',
  AI_CHAT: 'AIChat',
};
